### PR TITLE
Master

### PR DESCRIPTION
**Pull request by devinpearson**
Added more examples and some comments

### CODE REVIEW

**Comment by harrisonhjones** [comment]
Good work. Keep it up man :+1: Aside from the OAuth stuff I think we are almost feature complete

**Comment by devinpearson** [comment]
Cool no problem.

check through the js api client. you will see there is a few features im interested to see if they are worth adding
https://github.com/spark/spark-cli/blob/abd4cf98ca16af199f7b824cdf066ba8d8357072/lib/ApiClient.js#L154

compileCode,
downloadBinary,
sendPublicKey,
getEventStream,
publishEvent,
signalCore

**Comment by harrisonhjones** [comment]
Alright. Add them as issues and we'll get to tackling them?

Just looked at downloadBinary. What the heck does that do?

**Comment by devinpearson** [comment]
yeah some of them im not quite sure what they do. 

the signalCore function also eludes me

**Comment by harrisonhjones** [comment]
The signalCore function makes cores "shout rainbows". Just asked and got that answer

**Pull request merged**
