### PR TITLE
Master

### LINKED ISSUE #2: Generate a new access token
Not implemented (yet)

### PR DESCRIPTION
**Pull request by devinpearson**
changed the curl functions in to a single function.
added webhooks
added tokens

resolves #2, #3, #4, #5

### CODE REVIEW

**Comment by harrisonhjones** [comment]
Looks good. One point of question: Why doesn't get listToken, getToken, deleteToken used the stored access credentials (username & password) like the other functions which used the stored access token to do operations? Also, when/if it does, it should make a check to see if those credentials are defined.

**Comment by harrisonhjones** [comment]
Also, thanks for using `__FUNCTION__`. I completely forgot that magic constant existed! That's fantastic

**Comment by devinpearson** [comment]
Hey no worries. We can have it use the stored credentials. I didnt really give it much thought. It would be better to use the stored credentials. I tried to match your coding style as best I could.

Thought this would also be a good start as a contribution from my side as I had most of the functions in my code

**Comment by harrisonhjones** [comment]
You did a fantastic job. My style also isn't set in stone so I'm open to changes if you have suggestions. 

I'll pull this in a then one of us can make the stored credentials change

**Pull request merged**
